### PR TITLE
Release 0.2

### PR DESCRIPTION
**Pull request by andredevjs**
Preview: https://deploy-preview-153--fabulous-meringue-01474b.netlify.app/

# Wallet

## Metamask
- [ ] [Case NOSFT001](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft001---connect-wallet) - Connect Wallet Metamask | Tester @ 
- [ ] [Case NOSFT002](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft002---disconnect-wallet) - Disconnect Wallet Metamask | Tester @ 
- [ ] [Case NOSFT004](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft004---your-inscriptions) - Your inscriptions | Tester @ 
- [ ] [Case NOSFT005](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft005---your-inscriptions-search-filter) - Your inscriptions search filter | Tester @ 
- [ ] [Case NOSFT007](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft007---order-your-inscriptions) - Order your inscriptions | Tester @ 
- [ ] [Case NOSFT008](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft008---owned-inscription-details) - Owned Inscription details | Tester @ 
- [ ] [Case NOSFT009](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft009---send-inscription) - Send inscription | Tester @ 
- [ ] [Case NOSFT0010](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0010---boost-inscription) - Boost inscription | Tester @ 
- [ ] [Case NOSFT0011](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0011---sell-inscription) - Sell inscription | Tester @ 
- [ ] [Case NOSFT0012](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0012---sign-message) - Sign Message | Tester @ 
- [ ] [Case NOSFT0016](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0016---buy-inscription) - Buy inscription | Tester @ 
- [ ] [Case NOSFT0017](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0017---large-set-of-utxos-and-inscriptions) - Large set of utxos and inscriptions | Tester @ 

## Ordswap
- [x] [Case NOSFT001](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft001---connect-wallet) - Connect Wallet Metamask | Tester @andredevjs 
- [x] [Case NOSFT002](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft002---disconnect-wallet) - Disconnect Wallet Metamask | Tester @andredevjs  
- [x] [Case NOSFT004](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft004---your-inscriptions) - Your inscriptions | Tester @andredevjs 
- [x] [Case NOSFT005](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft005---your-inscriptions-search-filter) - Your inscriptions search filter | Tester @andredevjs 
- [x] [Case NOSFT007](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft007---order-your-inscriptions) - Order your inscriptions | Tester @andredevjs  
- [x] [Case NOSFT008](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft008---owned-inscription-details) - Owned Inscription details | Tester @andredevjs 
- [x] [Case NOSFT009](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft009---send-inscription) - Send inscription | Tester @andredevjs 
- [ ] [Case NOSFT0010](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0010---boost-inscription) - Boost inscription | Tester @andredevjs 🛑 - On boost, it is trying to sign with Alby, instead of Ordswap
- [ ] [Case NOSFT0011](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0011---sell-inscription) - Sell inscription | Tester @ 
- [x] [Case NOSFT0012](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0012---sign-message) - Sign Message | Tester @andredevjs  
- [ ] [Case NOSFT0016](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0016---buy-inscription) - Buy inscription | Tester @ 
- [x] [Case NOSFT0017](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0017---large-set-of-utxos-and-inscriptions) - Large set of utxos and inscriptions | Tester @andredevjs  

## Generative
- [ ] [Case NOSFT001](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft001---connect-wallet) - Connect Wallet Metamask | Tester @ 
- [ ] [Case NOSFT002](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft002---disconnect-wallet) - Disconnect Wallet Metamask | Tester @ 
- [ ] [Case NOSFT004](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft004---your-inscriptions) - Your inscriptions | Tester @ 
- [ ] [Case NOSFT005](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft005---your-inscriptions-search-filter) - Your inscriptions search filter | Tester @ 
- [ ] [Case NOSFT007](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft007---order-your-inscriptions) - Order your inscriptions | Tester @ 
- [ ] [Case NOSFT008](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft008---owned-inscription-details) - Owned Inscription details | Tester @ 
- [ ] [Case NOSFT009](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft009---send-inscription) - Send inscription | Tester @ 
- [ ] [Case NOSFT0010](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0010---boost-inscription) - Boost inscription | Tester @ 
- [ ] [Case NOSFT0011](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0011---sell-inscription) - Sell inscription | Tester @ 
- [ ] [Case NOSFT0012](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0012---sign-message) - Sign Message | Tester @ 
- [ ] [Case NOSFT0016](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0016---buy-inscription) - Buy inscription | Tester @ 
- [ ] [Case NOSFT0017](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0017---large-set-of-utxos-and-inscriptions) - Large set of utxos and inscriptions | Tester @ 

## Alby
- [x] [Case NOSFT001](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft001---connect-wallet) - Connect Wallet | Tester @topether21 
- [x] [Case NOSFT002](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft002---disconnect-wallet) - Disconnect Wallet | Tester @topether21 
- [x] [Case NOSFT004](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft004---your-inscriptions) - Your inscriptions | Tester @topether21 
- [x] [Case NOSFT005](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft005---your-inscriptions-search-filter) - Your inscriptions search filter | Tester @topether21 
- [x] [Case NOSFT007](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft007---order-your-inscriptions) - Order your inscriptions | Tester @topether21 
- [x] [Case NOSFT008](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft008---owned-inscription-details) - Owned Inscription details | Tester @ 
- [x] [Case NOSFT009](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft009---send-inscription) - Send inscription | Tester @topether21 
- [ ] [Case NOSFT0010](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0010---boost-inscription) - Boost inscription | Tester @ 
- [ ] [Case NOSFT0011](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0011---sell-inscription) - Sell inscription | Tester @ 
- [ ] [Case NOSFT0012](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0012---sign-message) - Sign Message | Tester @ 
- [ ] [Case NOSFT0016](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0016---buy-inscription) - Buy inscription | Tester @ 
- [ ] [Case NOSFT0017](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0017---large-set-of-utxos-and-inscriptions) - Large set of utxos and inscriptions | Tester @ 

---
- [ ] [Case NOSFT003](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft003---on-sale-slider) - On sale slider | Tester @ 
- [ ] [Case NOSFT0013](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft0013---filter-inscriptions-on-sale) - Filter Inscriptions on sale | Tester @ 
- [ ] [Case NOSFT014](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft014---filter-out-txt-inscriptions) - Filter out txt inscriptions | Tester @ 
- [ ] [Case NOSFT015](https://github.com/dannydeezy/nosft/wiki/NOSFT-QA#case-nosft015---order-inscriptions-on-sale) - Order inscriptions on sale | Tester @

### CODE REVIEW

**Review by habibitcoin — APPROVED** [review]
Ready to go!

QA'd on Metamask + Alby for sending, sending w/ turbo, listing, selling, buying

**Comment by topether21** [comment]
https://user-images.githubusercontent.com/126987350/236517872-d40e0d9b-0557-4e6e-abcf-5c80604f737f.mov

Switch accounts issue.
bc1pjnm9xhsr5hcf540g5xgacyvy4taw4txg0kjguqnd53472ft0u4kqmq0zg4 -> should have 2
bc1p6hsehjafcdzzht5shm4qmm3w2aspwlh843w5r9s33ejhhwesy9qss2hxhp -> should have 1

**Comment by topether21** [comment]
Notes: the wallet popup is always displayed after login.

**Comment by andredevjs** [comment]
@topether21 merged, can you re-test the failed case?

**Comment by jaca8602** [comment]
ALBY- 
Order inscriptions by date value and # works.
Send inscription - works, fees are extremely so still showing up as unconfirmed. Update: showed up as confirmed. Displayed confirmation modal, TXID showed. 
On sale slider works and loaded in a fair amount of time. 
Your inscriptions is not loading, this wallet has close to 100.
Sell inscription stalls when listing after accessing, reloaded and it worked. 
Large set of utxos and inscriptions - this worked but there were latency issues around loading my inscriptions. Had to quit and connect to my wallet again for it to eventually be working. 
Boost was successful with inscription that had only <500 sats. 
Filter inscriptions on sale successful, latency issue when clearing filter. 
Inscription 15fe35dc93c95ff8f591ad2a8c6ab90a59591a5ce8f2efad61792fc25994feb0i0 still showing up multiple times.



MetaMask - 

Wallet connects and displays inscriptions. 
Disconnect wallet - wallet data did not clean up after disconnect when switching to another wallet. When it eventually switched over to my MM, it showed inscriptions from my previous wallet later on in my session.
On Sale slider is experiencing latency issues and not loading inscription listings.
“Your inscriptions” worked with the two inscriptions I had in the MM wallet. 
When filtering by inscription #, the first inscription in my wallet showed up, when entering inscription # for the second nothing happened. 
Owned inscription details - had bad latency but details were eventually displayed.
Send and Boost - pending, confirmation modal not displayed, 
Sell inscription - was able to click to open up the modal, entering the inscription price, was able to provide proper signatures and clicking sell it gave me the loading wheel. When restarting the process and then clicking sell it worked, listing showed up in the view all on sale. 
Successfully am able to filter inscriptions and filter out txt inscriptions. Latency issue when clearing filter/hiding and unhiding txt.

GENERATIVE

Wallet Connect- Wallet connects, inscriptions are displayed.
Disconnect Wallet - When Generative wallet is disconnected and connects to different wallet, Generative wallet collection is displayed rather than connected wallet. 
On-Sale slider - txt inscriptions are showing (I don’t see txt filter added on generative wallet). Latency issue on the slider, but it does eventually load and the slider does eventually move automatically. 
 Your inscriptions - loads my inscription that I have in there, due to high fees I only have a low amount of inscriptions in each wallet (2-3), but inscriptions do appear in Generative wallet. 
Search filter is functioning for Generative Wallet, displays matching record, then when filter is cleared it goes back to normal state.

**Comment by topether21** [comment]
I can not load inscriptions @andredevjs 

https://deploy-preview-153--fabulous-meringue-01474b.netlify.app/inscription/6753d5b1c7a5db705a01548ddf955b8d9a163e2b0f0b07ad0a693e959c07fdbai0

image

**Pull request merged**
