### PR TITLE
Add search and sort functionality to gallery

### LINKED ISSUE #10: gallery should have search function
Should be able to search by txid, inscription id, utxo key, etc

### PR DESCRIPTION
**Pull request by avp1598**
Fixes #10 , #11 

What was added:

- Input field on gallery page
- Search by any of the properties inscriptionId, key, value, blocktime
- Sort by date
- Sort by value
- Change the marginTop css to 50px as I felt 100px was a bit too much 
- Added library match-sorter to help with the filtering

Watch the demo below

https://user-images.githubusercontent.com/24447702/224550359-f4229249-4e09-404d-8fb2-23e63c20bae1.mov

### CODE REVIEW

**Comment by andredevjs** [comment]
This one looks good.
We might want to abstract the search functionality since we would also like to filter the ordinals that we fetch from nostr.

We can have that as a separate PR.

**Comment by dannydeezy** [comment]
loving it!

**Comment by dannydeezy** [comment]
@avp1598 we just merged something to show inscription number.. could we add sort by inscription number?

**Comment by dannydeezy** [comment]
> @avp1598 we just merged something to show inscription number.. could we add sort by inscription number?

ill make a separate issue for this which we can do in a follow-up

**Pull request merged**
