### PR TITLE
Feature/dummy utxo api

### PR DESCRIPTION
**Pull request by habibitcoin**
Done:
- [x] Implement API to fetch dummy UTXO (if available) by address

Open Questions/To-dos:
- [ ] Should any additional supplemental APIs be created? 
- [ ] API returning a PSBT to create a dummy UTXO if not available
- [ ] API returning a PSBT with a dummy UTXO included if provided a sellers PSBT

### CODE REVIEW

**Comment by dannydeezy** [comment]
@habibitcoin a little risky here in a couple ways:
- if somebody has an unconfirmed utxo, the inscriptionId will not be present yet, and they could accidentally spend it (so maybe require 2 confs or something)
- if the inscription indexer service is delayed, can also cause people to spend their inscriptions unintentionally - this happened to Hiro wallet customers at one point I believe

**Comment by habibitcoin** [comment]
@dannydeezy maybe dumb question, but is it actually dangerous to use an inscription as a dummy UTXO? Wouldn't you always just get it back?

**Comment by habibitcoin** [comment]
Regardless, I think it's a good point because that could result in unexpected/suboptimal UX. Imagine if your dummy UTXO was an inscription listed for sale, you'd accidentally invalidate the listing

So no risk of losing the inscription, but still not great. Will put a check somehow for like 2 confs?

**Comment by andredevjs** [comment]
look at the implementation here: https://github.com/dannydeezy/nosft/pull/115/files#diff-7dc30f21f8bbb6a6c14075270aef4657c79781b802f3eb0b1038b5340a4aa5abR134

Should we add the 2 conf validation?

**Comment by dannydeezy** [comment]
> @dannydeezy maybe dumb question, but is it actually dangerous to use an inscription as a dummy UTXO? Wouldn't you always just get it back?

that's fine if if the first dummy UTXO input, because then the ordinal transfers to the top sat of the first output

but generally that should be avoided, not good practice

**Comment by habibitcoin** [comment]
Stale/irrelevant. Already implemented in mv2

**Pull request closed without merging**
